### ISSUE TITLE
Make pephub API accept query parameters

### ISSUE THREAD

**Issue by rafalstepien** [pepkit/pephub#53] opened 2022-10-05 16:00 UTC
Example request:

```
GET https://pephub.databio.org/pep/geo/GSE124224/convert?filter=csv?DATA=some/local/path&IMPORTANT_PARAMETER=value_of_this_parameter&VARIABLE=test
```

**Comment by nsheff** [comment] 2022-11-02 12:51
I think this is a duplicate of #3

**Closed as completed** 2022-11-03 14:19 UTC
Labels: duplicate, enhancement
