### ISSUE TITLE
UI invents a column name

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#343] opened 2024-07-05 23:20 UTC
When I paste in data and a column name is missing, the UI is inventing it.

This is really problematic.

Try pasting this in to a new pephub page:

<!DOCTYPE html>
<html>
<style>
table {
border: 1px solid black;
border-style: solid;
padding: 0px;
border-collapse: collapse;
}
td {
border: 1px solid black;
border-style: solid;
padding: 4px;
}
</style>
<body>

  | b | c
-- | -- | --
1 | 2 | 3
  |   |  

</body>
</html>

It will force you to have a `column_1` name! It almost seems like there is `afterPaste` content, but I know this isn't built into handsOnTable.

**Comment by nleroy917** [comment] 2024-07-16 20:11
### The source of the problem
The core problem here is that **there is a fundamental difference between the sample table data model in `handsontable` and the rest of our application/infrastructure**. PEPhub, pepdbagent, and company all treat sample tables as *lists of sample objects*. They look like this:
```
samples = [
  {
    sample_name: "sample1",
    genome: "hg38",
  },
  {
    sample_name: "sample2",
    genome: "hg19"
  }
]
```
This is very different from the way `handsontable` stores/handles data, which is a *list of lists*:
```
samples = [
  ["sample_name", "genome"],
  ["sample1", "hg38"],
  ["sample2", "hg19"],
]
```

### On the react side
This isn't a problem until one starts editing the samples. This is because what `handsontable` spits out as changes are *lists of lists*, and **at some point** these *must* be converted into a form that can be consumed by ultimately `peppy` since it drives all of our infrastructure; logistically, the endpoints require the *list of sample objects* representation. So, **at some point** before we send it off, we **must** convert that *list of lists* to a *list of sample objects* so we can save it. I do this as close to `handsontable` as possible since the rest of the application expects that *list of sample objects* representation. In fact, i just abstract it away and the sample table has this interface:

```tsx
const samples = [
  {
    sample_name: "sample1",
    genome: "hg38",
  },
  {
    sample_name: "sample2",
    genome: "hg19"
  }
]
  
<SampleTable
  value={samples}
  onChange={(newSamples: Sample[]) => console.log(newSamples)
/>

>>> spits out list of sample objects
```

This is nice, because as a developer you only need to think about samples as objects, not a list of lists. but it can lead to bugs...

### Source of bugs
This is the reason for a lot of weird bugs. For example, when a user creates a blank column like so:
<img width="448" alt="image" src="https://github.com/user-attachments/assets/24731c5e-9b0a-4fc7-b967-4bddaaee1427">
The table will try to return to the `onChange` handler *a list of sample objects* with `null` as an attribute. This isn't valid and thus, I create a dummy name for you instead based on the column number (`column_2`).

This is the reason you cannot have duplicate column names either, because when the table attempts to create the *list of sample objects* representation, it overwrites one of the attributes, since an object can't have two attributes with the same name!


### Solutions
Unfortunately, unless we completely alter our infrastructure and datamodel, we can't just let the user save whatever they want... **at some point in the bit-pipeline**, we need that *list of lists* representation to become a *list of sample objects* one. For this reason, the question becomes **when do we covert**? 

I think for the sample table editing, we can just kick the can down the pipeline a bit and convert right before we send off to the server and raise errors there. However, this could become frustrating, and it might produce unexpected results and shifted tables after saving...

I don't know the ultimate solution, but I wanted to get it all down here so people know the reason for trying to "guess" user behavior.

**Comment by nleroy917** [comment] 2024-07-17 13:40
Tracking here. There needs to sort of be a list of "edge cases" we need to watch for to guide the user and prevent weird behavior. I am switching the front-end data model to the *list of lists* approach and should make the UI less "draconian", but as I said it kicks the fundamental problem down the line: We can't save **bad** sample tables. What do we need to watch out for to warn the user?

- [ ] duplicate column names
- [ ] `null` columns (is this valid)?
- [ ] Do we let them try to save anyways (it will cause unexpected behavior), or do we warn/error on the UI and refuse to save?

**Comment by nleroy917** [comment] 2024-07-17 13:52
I think this is just a duplicate of #344

**Comment by nleroy917** [comment] 2024-07-17 18:05
See resolution in #344

**Closed as completed** 2024-07-24 15:04 UTC
Labels: likely solved, DX
